#!/usr/bin/env python3
"""
Prove ops/crawl_report.py counts this repository's own agents as its own, and
not as "human or unknown".

WHY THIS EXISTS
---------------
Measured 2026-09-29 over 8 days of the persistent access log: of 41,359
requests to this site, 16,441 were 6s-freshness, 8,746 the compose
healthcheck's wget, 3,721 6s-linkcheck, 2,970 6s-dashboard, 1,803
6s-success-indexnow, 800 6s-integrations and 80 6s-checkin. Roughly 84% of all
traffic to 6s-success.com is generated by this repository.

None of those agents matched any pattern in the report's table, so every one
was counted as "human or unknown". That is the report's largest bucket and the
one a reader is most likely to mistake for an audience: the run that afternoon
printed 78,295 of them, against a measured 48 real visitors in thirty days.
After the fix the same window reads 58,247 own tooling and 13,986 human or
unknown.

This report exists to answer one question, whether search engines read this
site, and while Search Console is unverified it is the only thing that can.
Its biggest number must not be its own monitoring.

Run:  python ops/tests/test_crawl_report_own_tooling.py
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "ops"))

import crawl_report as C                                       # noqa: E402

# Every agent string this repository is known to send, taken from the tools
# themselves rather than guessed: deploy_freshness.py, check_live_links.py,
# dashboard.py, indexnow.py, and the integrations and check-in workflows.
OURS = ("6s-freshness", "6s-linkcheck", "6s-dashboard",
        "6s-success-indexnow/1.0", "6s-integrations", "6s-checkin")


def case_every_known_own_agent_is_classified_as_ours():
    for ua in OURS:
        assert C.classify(ua) == "6S own tooling", (ua, C.classify(ua))


def case_no_own_agent_falls_into_human_or_unknown():
    for ua in OURS:
        assert C.classify(ua) != "human or unknown", ua


def case_a_real_browser_is_still_human_or_unknown():
    for ua in ("Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
               "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X)"):
        assert C.classify(ua) == "human or unknown", ua


def case_search_engines_are_not_shadowed_by_the_new_pattern():
    """The own-tooling pattern runs first, so prove it claims nothing else."""
    for ua, expect in (("Googlebot/2.1", "Googlebot"),
                       ("Googlebot-Image/1.0", "Googlebot-Image"),
                       ("bingbot/2.0", "Bingbot"),
                       ("OAI-SearchBot/1.0", "OAI-SearchBot"),
                       ("GPTBot/1.2", "GPTBot"),
                       ("ClaudeBot/1.0", "ClaudeBot"),
                       ("Applebot/0.1", "Applebot"),
                       ("PerplexityBot/1.0", "PerplexityBot"),
                       ("AhrefsBot/7.0", "SEO tools")):
        assert C.classify(ua) == expect, (ua, C.classify(ua))


def case_the_pattern_is_anchored_so_it_cannot_claim_a_third_party():
    """A stranger's agent that merely contains 6s must not read as ours."""
    for ua in ("SomeCrawler/1.0 (+http://example.com/6s-bot)",
               "Mozilla/5.0 x6s-something"):
        assert C.classify(ua) != "6S own tooling", ua


def case_own_tooling_is_not_counted_as_a_search_engine():
    for ua in OURS:
        assert C.purpose(C.classify(ua)) is None, ua


def main() -> int:
    cases = [v for k, v in sorted(globals().items()) if k.startswith("case_")]
    for c in cases:
        c()
        print("  ok  " + c.__name__)
    print("%d/%d cases passed" % (len(cases), len(cases)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
