#!/usr/bin/env python3
"""
Prove ops/preflight.py's gate_affiliate_report_current() catches the
generated affiliate reports drifting from what ops/affiliate_report.py
actually produces.

Found live 2026-09-24: ops/affiliate_report.py's CSV writer used Python's
csv.writer default line terminator (CRLF), while every other committed CSV
in this repository is LF, so every regeneration showed all 124 rows of
affiliate-link-input-needed.csv as changed with no real content difference.
Fixed at the generator; this tests the pure logic
(check_affiliate_report_current) with synthetic text, so it never touches
the real committed files.

Run:  python ops/tests/test_gate_affiliate_report_current.py
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(ROOT, "ops"))

import preflight                                               # noqa: E402

MATRIX = "# Affiliate compliance matrix\n\nGenerated by ops/affiliate_report.py on 2026-09-24. Do not hand-edit.\n"
EXCEPTIONS = "# Affiliate input exceptions\n\nGenerated by ops/affiliate_report.py on 2026-09-24 from the real account records.\n"
NEEDED = "product_id,merchant\nMPL-00001,target\nMPL-00002,target\n"


def main() -> int:
    fails = []

    # 1. Clean: freshly regenerated text matches committed text exactly,
    #    even though the embedded "on <date>" stamp would legitimately
    #    differ on a later run (both carry the same date here, but the
    #    comparison must not depend on that).
    problems = preflight.check_affiliate_report_current(
        MATRIX, EXCEPTIONS, NEEDED, MATRIX, EXCEPTIONS, NEEDED)
    if problems:
        fails.append("clean set wrongly flagged: %s" % problems)

    # 2. Only the date stamp differs (a run on a later day): must NOT flag.
    later_matrix = MATRIX.replace("2026-09-24", "2026-09-25")
    problems = preflight.check_affiliate_report_current(
        later_matrix, EXCEPTIONS, NEEDED, MATRIX, EXCEPTIONS, NEEDED)
    if problems:
        fails.append("a date-only difference was wrongly flagged: %s"
                      % problems)

    # 3. The real regression: the committed CSV carries CRLF line endings.
    crlf_needed = NEEDED.replace("\n", "\r\n")
    problems = preflight.check_affiliate_report_current(
        MATRIX, EXCEPTIONS, NEEDED, MATRIX, EXCEPTIONS, crlf_needed)
    if not any("CRLF" in p and "affiliate-link-input-needed.csv" in p
               for p in problems):
        fails.append("CRLF line endings in the committed CSV were NOT "
                      "caught: %s" % problems)

    # 4. Genuine stale data: the committed matrix no longer matches what
    #    the generator currently produces (a programme's status changed
    #    upstream but the matrix was never regenerated).
    stale_matrix = MATRIX.replace("2026-09-24", "2026-09-24") + "stale row\n"
    problems = preflight.check_affiliate_report_current(
        MATRIX, EXCEPTIONS, NEEDED, stale_matrix, EXCEPTIONS, NEEDED)
    if not any("AFFILIATE_COMPLIANCE_MATRIX.md" in p for p in problems):
        fails.append("stale matrix content was NOT caught: %s" % problems)

    if fails:
        print("FAIL")
        for f in fails:
            print("  -", f)
        return 1
    print("OK  gate_affiliate_report_current: 4/4 cases pass")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
