#!/usr/bin/env python3
"""
The affiliate programme's own paperwork, generated rather than typed.

WHY GENERATED
-------------
A compliance matrix and an exceptions list are only worth having if they are
true on the day somebody reads them. Hand-typed, they describe the programme
on the day they were written and quietly stop matching the moment a status
changes. Everything here is derived from the two files that actually decide
anything:

  ops/affiliate-accounts.json   the approval state, one record per programme
  ops/affiliate-catalogue.csv   the products and their offer fields

so the reports cannot disagree with the system they describe.

Run:  python ops/affiliate_report.py
"""
from __future__ import annotations

import csv
import datetime
import io
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ACCOUNTS = os.path.join(ROOT, "ops", "affiliate-accounts.json")
CATALOGUE = os.path.join(ROOT, "ops", "affiliate-catalogue.csv")

MATRIX = os.path.join(ROOT, "AFFILIATE_COMPLIANCE_MATRIX.md")
EXCEPTIONS = os.path.join(ROOT, "AFFILIATE_INPUT_EXCEPTIONS.md")
NEEDED = os.path.join(ROOT, "affiliate-link-input-needed.csv")

ENFORCED = [
    ("Disclosure sits above the links on every page carrying them",
     "ops/affiliate.py --check, run by gate_affiliate in ops/preflight.py"),
    ("No affiliate link in any delivered document (ebook, PDF, printable)",
     "ops/affiliate.py --check, 285 delivered documents scanned per run"),
    ("Disclosure wording must flip the day a programme is approved",
     "gate_affiliate_approved_claims_current in ops/preflight.py"),
    ("No link invented when a programme supplies no usable identifier",
     "ops/affiliate.py refuses a URL without an approved publisher id"),
    ("Retailer named before the click, sponsored rel on the link",
     "ops/build_zone_pages.py renders both; ops/audit_pages.py audits"),
    ("A recommendation states its reason in the product's own terms",
     "Why Recommended column, required by the catalogue reader"),
]


def load():
    acc = json.load(io.open(ACCOUNTS, encoding="utf-8"))
    progs = {k: v for k, v in acc.items()
             if isinstance(v, dict) and "status" in v}
    rows = list(csv.DictReader(io.open(CATALOGUE, encoding="utf-8")))
    return acc, progs, rows


def program_key(merchant: str) -> str:
    """Normalise a catalogue 'Merchant' value to its programme record key.

    The catalogue and ops/affiliate-accounts.json spell Home Depot
    differently ("homedepot" vs "home-depot"); every lookup against progs
    must go through this one normalisation or it silently misses.
    """
    return (merchant or "").strip().lower().replace(" ", "-").replace(
        "homedepot", "home-depot")


def missing_fields(p):
    """Exactly what this programme still needs before a link can be built."""
    out = []
    status = (p.get("status") or "").lower()
    if status.startswith("declined"):
        out.append("a fresh application or a different network: this one was "
                   "DECLINED, so no identifier will ever arrive on it")
    elif status.startswith("not applied"):
        out.append("an application: nobody has applied to this programme")
    elif "pending" in status:
        out.append("nothing from us; the programme has not answered yet")
    if not (p.get("publisher_id") or "").strip():
        out.append("publisher_id (public, appears in every link)")
    if not (p.get("deep_link_template") or "").strip() and status == "approved":
        out.append("deep_link_template, or a portal export of real URLs")
    return out


def main() -> int:
    acc, progs, rows = load()
    today = datetime.date.today().isoformat()
    approved = [k for k, v in progs.items()
                if (v.get("status") or "").lower().startswith("approved")]

    by_status = {}
    for k, v in progs.items():
        by_status.setdefault((v.get("status") or "unknown").lower(), []).append(k)

    m = ["# Affiliate compliance matrix", ""]
    m.append("Generated by ops/affiliate_report.py on %s. Do not hand-edit: "
             "it is rebuilt from ops/affiliate-accounts.json and "
             "ops/affiliate-catalogue.csv, the files that actually decide "
             "what the site does." % today)
    m += ["", "## Programmes", "",
          "| Programme | Network | Status | Publisher id | What it can do today |",
          "|---|---|---|---|---|"]
    for k in sorted(progs):
        p = progs[k]
        st = p.get("status") or "unknown"
        pid = (p.get("publisher_id") or "").strip() or "-"
        can = ("build links" if st.lower().startswith("approved")
               else "nothing: no link may be built")
        m.append("| %s | %s | **%s** | %s | %s |"
                 % (k, p.get("affiliate_network") or "-", st, pid, can))
    m += ["",
          "**Approved programmes: %d of %d.** Products with a usable "
          "affiliate link: **0 of %d**."
          % (len(approved), len(progs), len(rows)),
          "", "## Where each rule is enforced", "",
          "| Rule | Enforced by |", "|---|---|"]
    for rule, where in ENFORCED:
        m.append("| %s | %s |" % (rule, where))
    # Which retailers the catalogue actually points at, measured rather than
    # assumed. This is the fact that decides whether any approval is worth
    # anything, and it is not visible from the programme list alone.
    merch = {}
    for r in rows:
        k = (r.get("Merchant") or "(none)").strip().lower() or "(none)"
        merch[k] = merch.get(k, 0) + 1

    m += ["", "## Which retailers the catalogue actually points at", "",
          "| Merchant | Products | Programme state |", "|---|---|---|"]
    for k in sorted(merch, key=lambda x: -merch[x]):
        prog = progs.get(program_key(k))
        st = (prog or {}).get("status", "no programme record")
        m.append("| %s | %d | %s |" % (k, merch[k], st))
    m += ["",
          "**Read those two tables together and the position is sharper than "
          "either shows alone.** Every linked product in the catalogue points "
          "at target or homedepot. Both are Impact-routed. Both are declined. "
          "So the three programmes still pending (amazon, etsy, office-depot) "
          "could all approve tomorrow and **not one product would become "
          "linkable**, because no row points at any of them. Verified by "
          "simulating an approval: with amazon set to approved and a store tag "
          "pasted in, `affiliate.py --status` still reads 0 of 123 linkable.",
          "",
          "That leaves two routes, and they are the whole affiliate strategy:",
          "",
          "1. **Reopen Impact**, which unlocks the catalogue as it stands.",
          "2. **Re-source the 120 products to a retailer that can approve.** "
          "Amazon is the obvious candidate: it is in-house rather than "
          "Impact-routed, already pending, and carries almost everything in "
          "this catalogue. This is real work (120 rows re-verified against a "
          "different retailer) but it needs no permission to start.",
          ""]
    m += ["", "## The structural fact this matrix exists to show", "",
          "Five programmes (ace, home-depot, lowes, target, walmart) are not "
          "five separate rejections. They are ONE. All five route through "
          "Impact, and Impact declined the 6S Success Media Partner account "
          "(7700618) on 2026-08-29, citing its service agreement. Every "
          "Impact-routed programme is shut behind that single decision, so "
          "re-applying to them one at a time cannot work, and reading them as "
          "five independent refusals overstates how closed the market is.",
          "",
          "The unlock is one of: a new Impact application that answers the "
          "stated reason, a direct relationship outside Impact, or "
          "concentrating on the programmes that are not Impact-routed "
          "(amazon in-house, etsy via Rakuten, office-depot via CJ, plus "
          "container-store and wayfair, which have never been applied to).",
          ""]
    io.open(MATRIX, "w", encoding="utf-8", newline="\n").write("\n".join(m))

    e = ["# Affiliate input exceptions", ""]
    e.append("Generated by ops/affiliate_report.py on %s from the real "
             "account records. Each line is a field the system needs and "
             "does not have." % today)
    e += ["", "## The supplied input block asserted every programme was approved",
          "",
          "It is not. Read from ops/affiliate-accounts.json, whose statuses "
          "were last verified against the support inbox on 2026-09-01:", ""]
    for st in sorted(by_status):
        e.append("- **%s**: %s" % (st, ", ".join(sorted(by_status[st]))))
    e += ["",
          "**Approved: %d.** So no affiliate URL can be generated for any "
          "product yet, and none has been. ops/affiliate.py refuses to invent "
          "one, which is the correct behaviour and the reason there is no "
          "silent breakage to find here." % len(approved),
          "", "## Exactly what each programme still needs", ""]
    for k in sorted(progs):
        e.append("### %s" % k)
        for f in (missing_fields(progs[k]) or ["nothing outstanding"]):
            e.append("- %s" % f)
        note = (progs[k].get("notes") or "").strip()
        if note:
            e.append("- recorded note: %s" % note[:400])
        e.append("")
    io.open(EXCEPTIONS, "w", encoding="utf-8", newline="\n").write("\n".join(e))

    with io.open(NEEDED, "w", encoding="utf-8", newline="") as fh:
        w = csv.writer(fh, lineterminator="\n")
        w.writerow(["product_id", "product_standard_name", "merchant",
                    "merchant_sku", "missing_input", "blocked_by"])
        n = 0
        for r in rows:
            url = (r.get("Affiliate URL") or "").strip()
            # A URL in this column is NOT automatically a usable link. 120 of
            # the 123 are retailer SEARCH pages (target.com/s?searchTerm=...),
            # recorded honestly as "Verified search", and a search result is
            # not a product page: it can return a different item tomorrow, or
            # none. None of them carries tracking either, because no
            # programme is approved. So the only rows that are genuinely
            # ready are ones with a real product URL AND an approved
            # programme behind it, which today is zero.
            why = None
            if not url:
                why = "no URL at all"
            elif "searchterm=" in url.lower() or "/s?" in url.lower():
                # NOT a defect. ops/product_links.py explains why a search
                # for the product TYPE is the truthful form here: the
                # catalogue holds types, not products, and a verified product
                # URL turns into a different item without telling anybody.
                # Each of these was verified by rendering the search in a real
                # browser and matching result slugs, not by a status code.
                # What it still lacks is tracking, and only an approval gives
                # that.
                why = ("search for the product type, verified by render; "
                       "correct form for this catalogue, still has no "
                       "affiliate tracking")
            else:
                why = "URL present but carries no approved affiliate tracking"
            merch = (r.get("Merchant") or "").strip() or "(none chosen)"
            prog_key = program_key(merch)
            p = progs.get(prog_key)
            blocked = ("no programme record for this merchant" if p is None
                       else "%s: %s" % (prog_key, p.get("status")))
            w.writerow([r.get("Product ID", ""),
                        r.get("Product Standard Name", ""),
                        merch, r.get("Merchant SKU", ""),
                        why + "; needs an approved publisher id, then a "
                        "portal export or approved deep-link template",
                        blocked])
            n += 1

    print("  wrote AFFILIATE_COMPLIANCE_MATRIX.md")
    print("  wrote AFFILIATE_INPUT_EXCEPTIONS.md")
    print("  wrote affiliate-link-input-needed.csv (%d product(s))" % n)
    print("  programmes: %d tracked, %d approved" % (len(progs), len(approved)))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
