#!/usr/bin/env python3
"""
Build the Home Quest web app: a playable deck over all 114 micro zones.

WHAT IT IS
----------
The card deck's loop is draw a card, do one thing, put it down. That works on
paper for one room. The manual holds the same structure for 114 micro zones
across 20 rooms, which is far too much to print and exactly the right size for
something that remembers where you got to.

So this is the deck, generalised: every micro zone becomes six cards, one per
S, drawn from the same content the book and the site are built from. Nothing
here is written fresh. If the manual changes, the app changes.

WHY IT IS CLIENT SIDE
---------------------
The site is a static nginx bundle with no server and no accounts. That is a
constraint and also the right answer: a household reset app has no business
holding an account, and progress belongs in the browser of the person doing the
work. Everything persists to localStorage. Nothing is sent anywhere.

WHAT GETS TRIMMED, AND WHY
--------------------------
content.json is 702 KB. Roughly 390 KB of that is `shine_detail`, the deep
per-surface cleaning method, which belongs on the zone pages where somebody is
reading rather than in an app where somebody is holding a cloth. Dropping it
and two reference fields takes the payload to about a third, and the zone page
is one tap away for anybody who wants the detail.

Run:  python ops/build_quest.py
"""
from __future__ import annotations

import io
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = os.path.join(ROOT, "site")
SRC = os.path.join(ROOT, "content", "manual", "source", "content.json")
# The site's zone pages are named from the display name, not the raw zone name,
# so "Primary Prep Counter" is published at kitchen-the-primary-prep-counter.
# Using the raw name here produced a link on every card that 404s.
NAME_MAP = json.load(io.open(os.path.join(ROOT, "ops", "zone-name-map.json"),
                             encoding="utf-8"))

# Canonical order, asserted rather than trusted to dict iteration. Safety is
# the fourth S and that is the method's most distinctive claim.
SIX = ["sort", "straighten", "shine", "safety", "standardize", "sustain"]

# The six-S ramp, chaos to calm, straight from site/assets/css/site.css.
COLOURS = {"sort": "#CB4B36", "straighten": "#BC4B2A", "shine": "#D98A2B",
           "safety": "#DDA63A", "standardize": "#6E8B5B", "sustain": "#4E7A57"}

# What each pass is for, in the app's own voice. One line, because it sits
# above the instruction and must not compete with it.
PURPOSE = {
    "sort": "Decide what stays. Nothing else.",
    "straighten": "Give what stayed a home you can reach.",
    "shine": "Clean it, and see what the cleaning tells you.",
    "safety": "Fix what could hurt somebody. The fourth S, not the last.",
    "standardize": "Write down what good looks like, so it is not a memory.",
    "sustain": "Attach the reset to something that already happens.",
}


def display(room: str, zone: str) -> str:
    return NAME_MAP.get(f"{room}|{zone}", zone)


def slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def build_data() -> tuple[str, dict]:
    d = json.load(io.open(SRC, encoding="utf-8"))
    rooms, cards = [], 0

    for r in d["rooms"]:
        zones = []
        for z in r["zones"]:
            passes = z.get("passes") or {}
            steps = [{"s": s, "text": passes[s]} for s in SIX if passes.get(s)]
            if not steps:
                continue
            cards += len(steps)
            leave = z.get("leave_behind") or {}
            call = z.get("the_call") or {}
            zones.append({
                "zone": z["zone"],
                "session": z.get("session", ""),
                "purpose": z.get("purpose", ""),
                "done": z.get("done_looks_like", ""),
                "steps": steps,
                # The judgement call is the thing people get stuck on, so it
                # rides with the zone rather than being buried on a web page.
                "call": {"title": call.get("title", ""), "text": call.get("text", "")}
                        if call.get("text") else None,
                "watch": [{"q": w.get("question", ""), "t": w.get("text", "")}
                          for w in (z.get("watch_for") or []) if w.get("text")],
                "standard": leave.get("standard", ""),
                "trigger": leave.get("trigger", ""),
                "url": f"/zones/{slug(r['room'])}-{slug(display(r['room'], z['zone']))}",
            })
        if zones:
            rooms.append({"room": r["room"], "slug": slug(r["room"]), "zones": zones})

    payload = {"rooms": rooms, "six": SIX, "colours": COLOURS, "purpose": PURPOSE}
    js = ("/* Auto-generated by ops/build_quest.py from the Micro Zone Manual.\n"
          "   Do not edit. Change content.json and rebuild. */\n"
          "window.QUEST = " + json.dumps(payload, ensure_ascii=False,
                                         separators=(",", ":")) + ";\n")
    return js, {"rooms": len(rooms),
                "zones": sum(len(r["zones"]) for r in rooms),
                "cards": cards, "kb": len(js.encode()) // 1024}


def main() -> int:
    js, stats = build_data()
    out = os.path.join(SITE, "assets", "js", "quest-data.js")
    io.open(out, "w", encoding="utf-8", newline="").write(js)
    print(f"  quest-data.js  {stats['rooms']} rooms, {stats['zones']} zones, "
          f"{stats['cards']} cards, {stats['kb']} KB")

    # Guard the two claims the whole method rests on. A generated file is
    # exactly where a quiet reordering would survive unnoticed.
    data = json.loads(js[js.index("{"):js.rindex(";")])
    assert data["six"] == SIX, "the six S's are out of canonical order"
    assert data["six"][3] == "safety", "Safety must be the fourth S"
    print("  canon        Safety is the fourth S, order asserted")

    missing = []
    for r in data["rooms"]:
        for z in r["zones"]:
            page = os.path.join(SITE, z["url"].lstrip("/").replace("/", os.sep) + ".html")
            if not os.path.exists(page):
                missing.append(z["url"])
    if missing:
        print(f"  BROKEN       {len(missing)} zone link(s) point at no page:")
        for u in missing[:5]:
            print(f"                 {u}")
        return 1
    print(f"  links        all {stats['zones']} zone links resolve to a real page")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
