#!/usr/bin/env python3
"""
Make the Home Quest installable and make it work with no signal.

WHY
---
The Quest is used standing in a garage holding a box. That is exactly where
phones have no bars, and until now the app was a web page: no signal, no app.
It also could not be installed, so it lived behind a browser tab and a typed
URL, which is the difference between a thing people use once and a thing they
open on a Saturday morning.

A service worker fixes both, and it is also the honest first step toward the
native apps: a store-wrapped app that is not offline-capable and not installable
is just this page with a longer release cycle. Get this right and the wrapper
becomes a packaging job rather than a rewrite.

WHY THIS IS GENERATED
---------------------
The precache list has to name the exact asset URLs, and those URLs carry the
content hashes that ops/fingerprint_assets.py maintains. A hand written list
goes stale the first time a stylesheet changes, and a stale precache list is
worse than none: the worker would serve last week's CSS forever, confidently.

So the list is read out of the built page, and the cache version is derived from
those same hashes. Change any asset and the cache name changes with it, which
means old caches are dropped automatically and nobody has to remember.

ORDER MATTERS: run this AFTER ops/fingerprint_assets.py.

Run:  python ops/build_pwa.py
"""
from __future__ import annotations

import hashlib
import io
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = os.path.join(ROOT, "site")

# The pages the app itself needs. Deliberately NOT the whole site: precaching
# 168 pages would download several megabytes on first visit to save a few
# hundred kilobytes later, which is a bad trade on a phone.
SHELL_PAGES = ["/quest.html", "/"]

# THE ZONE ILLUSTRATIONS ARE DELIBERATELY NOT PRECACHED
# -----------------------------------------------------
# The Quest now shows one reviewed illustration per micro zone. There are 110
# of them in three widths and three formats, and addAll is atomic, so listing
# them here would mean every first visit downloading roughly a megabyte before
# the worker installs at all, in order to hold offline a picture of a room the
# person may never open. A single missing file would fail the whole install
# silently as well.
#
# The runtime cache-first rule in the fetch handler covers them instead: an
# image is cached the first time it is fetched, so every zone somebody has
# actually looked at is there in the garage, and one they have never opened
# shows its reserved sand-coloured box and its alt text. Nothing in the app
# depends on an image to work: the instruction, the standard, the safety notes
# and the timer are all text.
#
# The first-run picture is the one case worth re-examining, and it does not
# need precaching either. A first-run visitor by definition has no service
# worker yet, and the install prompt is gated behind holding a zone, so an
# installed app is never showing the first-run screen.

MANIFEST = {
    "name": "6S Success Home Quest",
    "short_name": "Home Quest",
    "description": ("Every micro zone in your house, one card at a time. Draw a "
                    "card, do one job, put it down."),
    "start_url": "/quest.html?from=app",
    "scope": "/",
    "display": "standalone",
    "orientation": "portrait",
    "background_color": "#22323C",
    "theme_color": "#22323C",
    "categories": ["lifestyle", "productivity", "utilities"],
    "lang": "en-US",
    "icons": [
        {"src": "/assets/img/icon-192.png", "sizes": "192x192", "type": "image/png"},
        {"src": "/assets/img/icon-512.png", "sizes": "512x512", "type": "image/png"},
        {"src": "/assets/img/icon-maskable-512.png", "sizes": "512x512",
         "type": "image/png", "purpose": "maskable"},
    ],
    # The two things somebody opens the app to do, straight from the launcher.
    "shortcuts": [
        {"name": "Draw a card", "url": "/quest.html?go=draw",
         "icons": [{"src": "/assets/img/icon-192.png", "sizes": "192x192"}]},
        {"name": "Your progress", "url": "/quest.html?go=map",
         "icons": [{"src": "/assets/img/icon-192.png", "sizes": "192x192"}]},
    ],
}

SW_TEMPLATE = '''/* Service worker for the 6S Success Home Quest.
 *
 * GENERATED by ops/build_pwa.py. Do not edit: the precache list carries the
 * content hashes of the assets it names, and hand editing it is how a worker
 * ends up serving last week's stylesheet forever.
 *
 * Cache name: __CACHE__
 * It is derived from the hashes below, so it changes exactly when the assets
 * change, and the activate step then drops every older cache automatically.
 */
var CACHE = "__CACHE__";
var PRECACHE = __PRECACHE__;

self.addEventListener("install", function (e) {
  /* skipWaiting so a returning visitor gets the new worker on this visit
     rather than the one after. Safe here: there is no server state to be out
     of step with, and the page reloads itself when control changes. */
  self.skipWaiting();
  e.waitUntil(caches.open(CACHE).then(function (c) {
    /* addAll is atomic and fails the whole install if one URL 404s, which is
       the behaviour we want: a half-populated cache is an app that works until
       it does not. */
    return c.addAll(PRECACHE);
  }));
});

self.addEventListener("activate", function (e) {
  e.waitUntil(caches.keys().then(function (keys) {
    return Promise.all(keys.map(function (k) {
      return k === CACHE ? null : caches.delete(k);
    }));
  }).then(function () { return self.clients.claim(); }));
});

self.addEventListener("fetch", function (e) {
  var req = e.request;
  if (req.method !== "GET") { return; }

  var url = new URL(req.url);
  if (url.origin !== self.location.origin) { return; }

  /* Never touch the analytics beacon. A cached beacon is a lie about traffic,
     and a queued one is worse. */
  if (url.pathname.indexOf("/stats/") === 0) { return; }

  /* Fingerprinted assets are immutable by definition: the URL changes when the
     bytes do. Cache first, and never revalidate.

     webp and avif were missing from this list, and that started mattering
     the moment the Quest itself began showing pictures. Every zone
     illustration the app draws is offered as AVIF first, WebP second and
     JPEG only as a last resort, so on a modern phone NONE of them matched
     this test: they fell past every branch below with no respondWith at
     all, went straight to the network, and were never put in the cache.
     Offline that is not a slower image, it is no image, permanently, even
     for a zone somebody had already opened twice. And a <picture> gives no
     second chance: once the browser has chosen a <source> it does not fall
     back to the next one when that file fails, so a JPEG sitting in the
     cache would never have been reached either.

     Safe to cache first for the same reason the JPEGs already are: an
     image here is replaced by adding a file, never by editing one. */
  if (url.search.indexOf("v=") >= 0 ||
      /\\.(png|jpe?g|webp|avif|svg|ico|woff2?)$/.test(url.pathname)) {
    e.respondWith(caches.match(req).then(function (hit) {
      return hit || fetch(req).then(function (res) {
        if (res.ok) {
          var copy = res.clone();
          caches.open(CACHE).then(function (c) { c.put(req, copy); });
        }
        return res;
      });
    }));
    return;
  }

  /* HTML is network first, because a page held is a page whose asset
     fingerprints are held too. Falling back to cache is what makes the app work
     in a garage. */
  if (req.mode === "navigate" || (req.headers.get("accept") || "").indexOf("text/html") >= 0) {
    e.respondWith(
      fetch(req).then(function (res) {
        if (res.ok) {
          var copy = res.clone();
          caches.open(CACHE).then(function (c) { c.put(req, copy); });
        }
        return res;
      }).catch(function () {
        return caches.match(req).then(function (hit) {
          /* An unvisited page offline falls back to the app itself, which is
             the one page somebody actually came to use. */
          return hit || caches.match("/quest.html");
        });
      })
    );
  }
});
'''


def main() -> int:
    page = io.open(os.path.join(SITE, "quest.html"), encoding="utf-8").read()

    # The exact asset URLs this page loads, hashes and all.
    assets = re.findall(r'(?:href|src)="((?:/|(?!https?:))[^"]*?'
                        r'assets/[^"]+?\.(?:css|js)(?:\?v=[0-9a-f]+)?)"', page)
    assets = ["/" + a.lstrip("/") for a in dict.fromkeys(assets)]

    icons = ["/assets/img/icon-192.png", "/assets/img/icon-512.png",
             "/assets/img/icon-maskable-512.png", "/assets/img/apple-touch-icon.png"]

    precache = SHELL_PAGES + assets + icons + ["/manifest.webmanifest"]

    # Written before the existence check below, because the manifest is itself
    # precached and the check is not a formality: addAll is atomic, so one
    # missing file fails the whole install and the app silently never caches.
    io.open(os.path.join(SITE, "manifest.webmanifest"), "w",
            encoding="utf-8", newline="").write(json.dumps(MANIFEST, indent=1))

    missing = [p for p in precache
               if not os.path.exists(os.path.join(SITE, p.split("?")[0].lstrip("/") or "index.html"))]
    assert not missing, ("precache names files that are not there, which would "
                         f"fail the install atomically: {missing}")

    # The cache name changes exactly when the precached content changes.
    version = hashlib.sha256("\n".join(precache).encode()).hexdigest()[:10]

    sw = (SW_TEMPLATE
          .replace("__CACHE__", f"6s-quest-{version}")
          .replace("__PRECACHE__", json.dumps(precache, indent=2)))
    io.open(os.path.join(SITE, "sw.js"), "w", encoding="utf-8", newline="").write(sw)

    print(f"  site/manifest.webmanifest   {len(MANIFEST['icons'])} icons, "
          f"{len(MANIFEST['shortcuts'])} launcher shortcuts")
    print(f"  site/sw.js                  cache 6s-quest-{version}, "
          f"{len(precache)} files precached")
    for p in precache:
        print(f"    {p}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
