"""Generate the mobile app's card corpus from the one the website already uses.

Prompt 3 of the mobile super prompt asks for a "canonical content pipeline". The
temptation is to copy quest-data.js into the app folder and move on. This
repository has spent a fortnight paying for exactly that shortcut: mcp/content
.json drifted from the manual for twelve days and blocked an image publish, 123
of 161 duplicated filenames across the estate have diverged, and the agents that
run had quietly stopped matching the agents in git.

So the app does not get a copy. It gets a build product, regenerated from
site/assets/js/quest-data.js, which is itself generated by ops/build_quest.py
from the Micro Zone Manual. One source, two consumers, and a gate that fails if
the derived file falls behind.

The transform is deliberately small. The website ships a JavaScript file with an
assignment on the front so a browser can load it with a script tag; the app
wants plain JSON it can import. Everything else, the rooms, the zones, the six
passes and their text, passes through untouched, because the moment this starts
reshaping content the two products begin to diverge in what they teach.

Run:  python ops/build_mobile_corpus.py
      python ops/build_mobile_corpus.py --check    (exit 1 if stale)
"""
from __future__ import annotations

import hashlib
import io
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "site", "assets", "js", "quest-data.js")
OUT = os.path.join(ROOT, "mobile", "quest-app", "assets", "quest-corpus.json")

# Zone pictures, bundled rather than fetched: the app footer promises nothing
# is sent anywhere, and the 106 approved 320px JPEGs total 1.4 MB (measured
# 2026-09-15). React Native needs a static require() per image, so the map is
# generated beside the corpus instead of written by hand.
HERO_SRC = os.path.join(ROOT, "site", "assets", "zones")
HERO_DIR = os.path.join(ROOT, "mobile", "quest-app", "assets", "zones")
HERO_MAP = os.path.join(ROOT, "mobile", "quest-app", "assets", "zoneHeroes.js")


def load_source() -> dict:
    """The website's corpus, as data.

    quest-data.js is `window.QUEST = { ... };` with a comment on top. Slicing
    from the first brace to the last is enough and avoids depending on the
    exact preamble, which build_quest.py owns and may reword.
    """
    s = io.open(SRC, encoding="utf-8").read()
    start = s.index("{")
    end = s.rindex("}")
    return json.loads(s[start:end + 1])


def build() -> dict:
    data = load_source()
    rooms = data.get("rooms", [])

    zones = []
    for r in rooms:
        for z in r.get("zones", []):
            zones.append({
                "room": r.get("room"),
                "roomSlug": r.get("slug"),
                "zone": z.get("zone"),
                "session": z.get("session"),
                "purpose": z.get("purpose"),
                "done": z.get("done"),
                "steps": z.get("steps", []),
                # Reviewed zone illustration stem as the web Quest carries it:
                # only for zones a human approved, else None. See hero_plan().
                "img": z.get("img") or None,
                # The zone's published YouTube id, for the 12 zones that have
                # one. Carried so the app can offer the same "watch this zone"
                # the web app does; a link only, so nothing is requested from
                # YouTube until somebody presses it. Absent for the rest.
                "video": z.get("video") or None,
            })

    # Flattened, because the app draws a card by zone and pass rather than
    # walking a room tree, and a flat list keeps the phone's work trivial.
    # The room tree is kept alongside so room mode does not need a second pass.
    return {
        "generatedFrom": "site/assets/js/quest-data.js",
        "generatedBy": "ops/build_mobile_corpus.py",
        "doNotEdit": "Regenerate instead. This is a build product.",
        "sourceSha256": hashlib.sha256(
            io.open(SRC, "rb").read().replace(b"\r\n", b"\n")).hexdigest(),
        "roomCount": len(rooms),
        "zoneCount": len(zones),
        "cardCount": sum(len(z["steps"]) for z in zones),
        "rooms": [{"room": r.get("room"), "slug": r.get("slug"),
                   "zoneCount": len(r.get("zones", []))} for r in rooms],
        "zones": zones,
    }


def hero_plan(corpus: dict) -> tuple:
    """(map text, {destination path: source path}) for every zone with an img.

    Sources are the -sm.jpg files the site already publishes (320x240). The app
    shows them as a header thumbnail, the one place the web Quest card allows a
    picture. A stem with no source file is a hard error, not a skipped zone:
    quest-data.js carries only approved stems, and a silent skip would be a
    picture quietly missing from one install.
    """
    stems = sorted({z["img"] for z in corpus["zones"] if z.get("img")})
    files, missing = {}, []
    for stem in stems:
        src = os.path.join(HERO_SRC, stem + "-sm.jpg")
        if not os.path.exists(src):
            missing.append(os.path.relpath(src, ROOT))
        files[os.path.join(HERO_DIR, stem + ".jpg")] = src
    if missing:
        raise SystemExit("  approved zone picture(s) missing from the site: %s"
                         % ", ".join(missing[:5]))
    q = chr(34)
    lines = ["/* Generated by ops/build_mobile_corpus.py. Do not edit; regenerate.",
             " * One static require per approved zone illustration: React Native",
             " * cannot require a computed path. Keyed by the corpus zone img. */",
             "module.exports = {"]
    lines += ["  " + q + s + q + ": require(" + q + "./zones/" + s + ".jpg" + q + "),"
              for s in stems]
    lines += ["};", ""]
    return chr(10).join(lines), files


def hero_problems(corpus: dict = None) -> list:
    """Every way the bundled pictures differ from what build() implies."""
    corpus = corpus or build()
    text, files = hero_plan(corpus)
    out = []
    have = io.open(HERO_MAP, encoding="utf-8").read() if os.path.exists(HERO_MAP) else None
    if have != text:
        out.append("assets/zoneHeroes.js is %s" % ("missing" if have is None else "stale"))
    for dest, src in sorted(files.items()):
        name = os.path.basename(dest)
        if not os.path.exists(dest):
            out.append("assets/zones/%s is missing" % name)
        elif open(dest, "rb").read() != open(src, "rb").read():
            out.append("assets/zones/%s differs from the site copy" % name)
    if os.path.isdir(HERO_DIR):
        for f in sorted(os.listdir(HERO_DIR)):
            if os.path.join(HERO_DIR, f) not in files:
                out.append("assets/zones/%s is not an approved zone picture" % f)
    return out


def write_heroes(corpus: dict) -> tuple:
    text, files = hero_plan(corpus)
    os.makedirs(HERO_DIR, exist_ok=True)
    copied = removed = 0
    for dest, src in files.items():
        data = open(src, "rb").read()
        if not os.path.exists(dest) or open(dest, "rb").read() != data:
            open(dest, "wb").write(data)
            copied += 1
    for f in os.listdir(HERO_DIR):
        p = os.path.join(HERO_DIR, f)
        if p not in files:
            os.remove(p)
            removed += 1
    io.open(HERO_MAP, "w", encoding="utf-8", newline="").write(text)
    return len(files), copied, removed


def main() -> int:
    want = build()
    text = json.dumps(want, ensure_ascii=False, indent=1) + "\n"

    if "--check" in sys.argv:
        if not os.path.exists(OUT):
            print("  the mobile corpus has never been built. Run: "
                  "python ops/build_mobile_corpus.py")
            return 1
        have = io.open(OUT, encoding="utf-8").read()
        if have != text:
            print("  the mobile corpus is stale against "
                  "site/assets/js/quest-data.js. Run: "
                  "python ops/build_mobile_corpus.py")
            return 1
        problems = hero_problems(want)
        if problems:
            print("  %d zone picture problem(s), e.g. %s. Run: "
                  "python ops/build_mobile_corpus.py" % (len(problems), problems[0]))
            return 1
        print("  the mobile corpus matches the website's, %d zones, %d cards"
              % (want["zoneCount"], want["cardCount"]))
        return 0

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    io.open(OUT, "w", encoding="utf-8", newline="").write(text)
    n, copied, removed = write_heroes(want)
    print("  zone pictures: %d bundled (%d copied, %d removed)" % (n, copied, removed))
    print("  wrote %s" % os.path.relpath(OUT, ROOT).replace(os.sep, "/"))
    print("  %d rooms, %d zones, %d cards, %d KB"
          % (want["roomCount"], want["zoneCount"], want["cardCount"],
             len(text) // 1024))
    return 0


if __name__ == "__main__":
    sys.exit(main())
