"""Generate the mobile app's card corpus from the one the website already uses.

Prompt 3 of the mobile super prompt asks for a "canonical content pipeline". The
temptation is to copy quest-data.js into the app folder and move on. This
repository has spent a fortnight paying for exactly that shortcut: mcp/content
.json drifted from the manual for twelve days and blocked an image publish, 123
of 161 duplicated filenames across the estate have diverged, and the agents that
run had quietly stopped matching the agents in git.

So the app does not get a copy. It gets a build product, regenerated from
site/assets/js/quest-data.js, which is itself generated by ops/build_quest.py
from the Micro Zone Manual. One source, two consumers, and a gate that fails if
the derived file falls behind.

The transform is deliberately small. The website ships a JavaScript file with an
assignment on the front so a browser can load it with a script tag; the app
wants plain JSON it can import. Everything else, the rooms, the zones, the six
passes and their text, passes through untouched, because the moment this starts
reshaping content the two products begin to diverge in what they teach.

Run:  python ops/build_mobile_corpus.py
      python ops/build_mobile_corpus.py --check    (exit 1 if stale)
"""
from __future__ import annotations

import hashlib
import io
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "site", "assets", "js", "quest-data.js")
OUT = os.path.join(ROOT, "mobile", "quest-app", "assets", "quest-corpus.json")


def load_source() -> dict:
    """The website's corpus, as data.

    quest-data.js is `window.QUEST = { ... };` with a comment on top. Slicing
    from the first brace to the last is enough and avoids depending on the
    exact preamble, which build_quest.py owns and may reword.
    """
    s = io.open(SRC, encoding="utf-8").read()
    start = s.index("{")
    end = s.rindex("}")
    return json.loads(s[start:end + 1])


def build() -> dict:
    data = load_source()
    rooms = data.get("rooms", [])

    zones = []
    for r in rooms:
        for z in r.get("zones", []):
            zones.append({
                "room": r.get("room"),
                "roomSlug": r.get("slug"),
                "zone": z.get("zone"),
                "session": z.get("session"),
                "purpose": z.get("purpose"),
                "done": z.get("done"),
                "steps": z.get("steps", []),
            })

    # Flattened, because the app draws a card by zone and pass rather than
    # walking a room tree, and a flat list keeps the phone's work trivial.
    # The room tree is kept alongside so room mode does not need a second pass.
    return {
        "generatedFrom": "site/assets/js/quest-data.js",
        "generatedBy": "ops/build_mobile_corpus.py",
        "doNotEdit": "Regenerate instead. This is a build product.",
        "sourceSha256": hashlib.sha256(
            io.open(SRC, "rb").read().replace(b"\r\n", b"\n")).hexdigest(),
        "roomCount": len(rooms),
        "zoneCount": len(zones),
        "cardCount": sum(len(z["steps"]) for z in zones),
        "rooms": [{"room": r.get("room"), "slug": r.get("slug"),
                   "zoneCount": len(r.get("zones", []))} for r in rooms],
        "zones": zones,
    }


def main() -> int:
    want = build()
    text = json.dumps(want, ensure_ascii=False, indent=1) + "\n"

    if "--check" in sys.argv:
        if not os.path.exists(OUT):
            print("  the mobile corpus has never been built. Run: "
                  "python ops/build_mobile_corpus.py")
            return 1
        have = io.open(OUT, encoding="utf-8").read()
        if have != text:
            print("  the mobile corpus is stale against "
                  "site/assets/js/quest-data.js. Run: "
                  "python ops/build_mobile_corpus.py")
            return 1
        print("  the mobile corpus matches the website's, %d zones, %d cards"
              % (want["zoneCount"], want["cardCount"]))
        return 0

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    io.open(OUT, "w", encoding="utf-8", newline="").write(text)
    print("  wrote %s" % os.path.relpath(OUT, ROOT).replace(os.sep, "/"))
    print("  %d rooms, %d zones, %d cards, %d KB"
          % (want["roomCount"], want["zoneCount"], want["cardCount"],
             len(text) // 1024))
    return 0


if __name__ == "__main__":
    sys.exit(main())
