#!/usr/bin/env python3
"""
Propagate the site footer from site/about.html to every other page.

WHY
---
resources.html is generated by build_resources.py, which lifts its own
header and footer from about.html at build time (see build_resources.py's
own _chrome()). build_articles.py, build_zone_pages.py and build_zone_index.py
then lift their chrome from resources.html in turn. That chain covers the
generated pages, but roughly 150 hand-authored top-level pages (index.html,
book.html, shop.html, corporate.html, consulting.html, deck.html, and so on)
each carry their own literal copy of the same footer HTML, kept in sync only
by whoever last edited it remembering to search-and-replace everywhere.
gate_footer_consistent (ops/preflight.py) catches drift after the fact; this
script is how a footer change gets applied everywhere in the first place,
the same role wire_nav.py already plays for the primary nav.

WHAT THIS DELIBERATELY DOES NOT DO
-----------------------------------
It does not touch downloads/ (shipped artefacts, not site pages) or the two
pages gate_footer_consistent already treats as deliberately footer-less:
invest.html (its own minimal investor footer) and
deck/entryway-print-and-play.html (a short notice, no site footer at all).

Idempotent. Run after editing about.html's footer, before any generator that
lifts chrome from about.html or resources.html, so their own output already
carries the new footer and gate_generator_ownership's regenerate-and-diff
check has nothing to catch.
"""
from __future__ import annotations

import glob
import io
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = os.path.join(ROOT, "site")
CANON_PATH = os.path.join(SITE, "about.html")

NO_FOOTER_BY_DESIGN = {"invest.html", "deck/entryway-print-and-play.html"}

FOOT_RE = re.compile(r'<footer class="site-footer">.*?</footer>', re.S)


def canonical_footer() -> str:
    src = io.open(CANON_PATH, encoding="utf-8").read()
    m = FOOT_RE.search(src)
    if not m:
        raise SystemExit("about.html has no <footer class=\"site-footer\">; nothing to propagate")
    return m.group(0)


def with_prefix(foot: str, prefix: str) -> str:
    if not prefix:
        return foot
    return re.sub(r'(href|src)="(?!https?:|#|mailto:|/)([^"]+)"',
                  r'\1="%s\2"' % prefix, foot)


def main() -> int:
    canon = canonical_footer()
    n = 0
    for f in sorted(glob.glob(os.path.join(SITE, "**", "*.html"), recursive=True)):
        rel = os.path.relpath(f, SITE).replace(os.sep, "/")
        if rel.startswith("downloads/") or rel in NO_FOOTER_BY_DESIGN:
            continue
        s = io.open(f, encoding="utf-8").read()
        m = FOOT_RE.search(s)
        if not m:
            continue

        # The prefix a page needs is the one its existing footer links
        # already use, read from the markup rather than derived from the
        # path, so a page in a directory nobody anticipated still gets
        # working links.
        pre = ""
        depth = re.search(r'href="((?:\.\./)+)', m.group(0))
        if depth:
            pre = depth.group(1)
        elif rel.count("/"):
            pre = "../" * rel.count("/")

        new = with_prefix(canon, pre)
        if new == m.group(0):
            continue
        s2 = s[:m.start()] + new + s[m.end():]
        io.open(f, "w", encoding="utf-8", newline="").write(s2)
        n += 1

    print(f"  footer rewritten on {n} pages")

    # A footer link that 404s is worse than a missing one.
    bad = []
    for f in glob.glob(os.path.join(SITE, "**", "*.html"), recursive=True):
        rel = os.path.relpath(f, SITE).replace(os.sep, "/")
        if rel.startswith("downloads/"):
            continue
        s = io.open(f, encoding="utf-8").read()
        m = FOOT_RE.search(s)
        if not m:
            continue
        for href in re.findall(r'href="([^"]+)"', m.group(0)):
            if href.startswith(("http:", "https:", "mailto:", "#")):
                continue
            target = os.path.normpath(os.path.join(os.path.dirname(f), href.split("?")[0].split("#")[0]))
            if os.path.isdir(target):
                target = os.path.join(target, "index.html")
            if not os.path.exists(target) and not os.path.exists(target + ".html"):
                bad.append((rel, href))
    assert not bad, f"footer links that resolve to nothing: {bad[:6]}"
    print(f"  every footer link on every page resolves")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
