"""Publish zone videos to youtube.com/@6SSuccess, with captions, resumably.

456 videos are built and 12 are public. That gap is the whole problem: the
media pipeline's output cannot help anybody find us while it sits on a disk.
The 12 that are live were posted by hand, which is why only 12 are live.

This uploads by API instead. It reads the metadata already generated by
ops/build_youtube_metadata.py, uploads the video, sets the title, description
and tags, and attaches the caption track as a real text track rather than
relying on the words burned into the picture.

WHAT IT REFUSES TO DO
  - Upload the same zone twice. YouTube cannot replace a video file after
    upload, so a double post means a duplicate that has to be deleted by hand.
    Every success is recorded in ops/youtube-published.json and checked first.
  - Claim success it did not observe. A video is recorded as published only
    after the API returns an id, and the caption only after its own call
    returns. A failed caption on a successful video is reported, not hidden.
  - Delete or modify anything already on the channel.

ONE TIME SETUP, WHICH ONLY THE OWNER CAN DO
  Uploading requires OAuth against the Google account that owns the channel.
  An API key is not sufficient for writes, so there is no way around this. See
  OWNER-ACTIONS.md for the exact steps; it takes about five minutes and never
  needs repeating. Put the downloaded file at ops/youtube-client-secret.json.

    python ops/youtube_upload.py --check          what would happen, no upload
    python ops/youtube_upload.py --room Entryway  publish one room
    python ops/youtube_upload.py --limit 5        publish the next five
"""
from __future__ import annotations

import argparse
import io
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
META = os.path.join(ROOT, "build", "video", "youtube")
VIDEO = os.path.join(ROOT, "build", "video", "zones-narrated")
SECRET = os.path.join(ROOT, "ops", "youtube-client-secret.json")
TOKEN = os.path.join(ROOT, "ops", "youtube-token.json")
LEDGER = os.path.join(ROOT, "ops", "youtube-published.json")
SCOPES = ["https://www.googleapis.com/auth/youtube.upload",
          "https://www.googleapis.com/auth/youtube.force-ssl"]


def ledger() -> dict:
    if os.path.exists(LEDGER):
        try:
            return json.load(io.open(LEDGER, encoding="utf-8"))
        except ValueError:
            # A corrupt ledger must not read as "nothing published", because
            # that would re-upload the whole channel as duplicates.
            raise SystemExit("  ops/youtube-published.json is unreadable. "
                             "Refusing to upload: I cannot tell what is "
                             "already live.")
    return {}


def record(slug: str, entry: dict) -> None:
    d = ledger()
    d[slug] = entry
    io.open(LEDGER, "w", encoding="utf-8", newline="").write(
        json.dumps(d, indent=1, ensure_ascii=False) + "\n")


def jobs(room: str | None):
    """Every zone with metadata and a rendered wide video, minus the published.

    The wide 16:9 file is the upload. Shorts are a separate distribution
    decision and are not posted by this tool.
    """
    done = ledger()
    out = []
    if not os.path.isdir(META):
        return out
    for f in sorted(os.listdir(META)):
        if not f.endswith(".json") or f == "playlists.json":
            continue
        m = json.load(io.open(os.path.join(META, f), encoding="utf-8"))
        if room and m.get("room") != room:
            continue
        if m["slug"] in done:
            continue
        mp4 = os.path.join(VIDEO, m["slug"] + "-16x9.mp4")
        srt = os.path.join(VIDEO, m["slug"] + "-16x9.srt")
        if not os.path.exists(mp4):
            continue
        out.append((m, mp4, srt if os.path.exists(srt) else None))
    return out


def service():
    from google.auth.transport.requests import Request
    from google.oauth2.credentials import Credentials
    from google_auth_oauthlib.flow import InstalledAppFlow
    from googleapiclient.discovery import build

    creds = None
    if os.path.exists(TOKEN):
        creds = Credentials.from_authorized_user_file(TOKEN, SCOPES)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            if not os.path.exists(SECRET):
                raise SystemExit(
                    "  BLOCKED: no OAuth client at ops/youtube-client-secret."
                    "json.\n  This is the one step I cannot do: it needs the "
                    "Google account\n  that owns the channel. See "
                    "OWNER-ACTIONS.md. Everything else is ready.")
            creds = InstalledAppFlow.from_client_secrets_file(
                SECRET, SCOPES).run_local_server(port=0)
        io.open(TOKEN, "w", encoding="utf-8").write(creds.to_json())
    return build("youtube", "v3", credentials=creds)


def upload_one(yt, m: dict, mp4: str, srt: str | None) -> dict:
    from googleapiclient.http import MediaFileUpload

    body = {
        "snippet": {
            "title": m["title"],
            "description": m["description"],
            "tags": m["tags"],
            "categoryId": m.get("categoryId", "26"),
            "defaultLanguage": "en",
        },
        "status": {
            "privacyStatus": m.get("privacyStatus", "public"),
            "selfDeclaredMadeForKids": False,
        },
    }
    req = yt.videos().insert(
        part="snippet,status", body=body,
        media_body=MediaFileUpload(mp4, chunksize=8 * 1024 * 1024,
                                   resumable=True, mimetype="video/mp4"))
    resp, prog = None, None
    while resp is None:
        prog, resp = req.next_chunk()
        if prog:
            sys.stdout.write("\r    uploading %3d%%" % int(prog.progress() * 100))
            sys.stdout.flush()
    sys.stdout.write("\r")
    vid = resp["id"]

    caption = "not attempted"
    if srt:
        try:
            yt.captions().insert(
                part="snippet",
                body={"snippet": {"videoId": vid, "language": "en",
                                  "name": "English", "isDraft": False}},
                media_body=MediaFileUpload(srt, mimetype="application/octet-stream")
            ).execute()
            caption = "uploaded"
        except Exception as e:                                  # noqa: BLE001
            # The video is live either way. Say the caption failed rather than
            # letting a green line imply it worked.
            caption = "FAILED: %s" % type(e).__name__
    else:
        caption = "no srt on disk"

    return {"video_id": vid, "url": "https://youtu.be/" + vid,
            "title": m["title"], "room": m["room"], "caption": caption}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--room")
    ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()

    todo = jobs(a.room)
    if a.limit:
        todo = todo[:a.limit]
    done = ledger()

    print("  already published : %d" % len(done))
    print("  ready to publish  : %d%s"
          % (len(todo), (" (room %s)" % a.room) if a.room else ""))
    missing_caps = [m["slug"] for m, _, s in todo if s is None]
    if missing_caps:
        print("  WITHOUT captions  : %d %s"
              % (len(missing_caps), missing_caps[:3]))
    if a.check:
        for m, _, _ in todo[:10]:
            print("     %-40s %s" % (m["slug"][:40], m["title"][:44]))
        print("  --check only, nothing uploaded")
        return 0
    if not todo:
        print("  nothing to do")
        return 0

    yt = service()
    ok, failed = 0, []
    for m, mp4, srt in todo:
        try:
            r = upload_one(yt, m, mp4, srt)
            record(m["slug"], r)
            ok += 1
            print("  live  %-38s %s  captions: %s"
                  % (m["slug"][:38], r["url"], r["caption"]))
        except Exception as e:                                  # noqa: BLE001
            failed.append((m["slug"], "%s: %s" % (type(e).__name__, str(e)[:90])))
            print("  FAIL  %-38s %s" % (m["slug"][:38], type(e).__name__))
            # A quota error will fail every remaining item identically, so
            # stop rather than burning the list into a wall of failures.
            if "quota" in str(e).lower():
                print("  Daily upload quota reached. Stopping; run again "
                      "tomorrow and it resumes where it stopped.")
                break

    print()
    print("  published this run: %d" % ok)
    print("  failed            : %d" % len(failed))
    for s, e in failed[:5]:
        print("     %s: %s" % (s, e))
    return 0 if ok and not failed else (1 if failed else 0)


if __name__ == "__main__":
    sys.exit(main())
